#+TITLE: FFS, FFS!
#+DESCRIPTION: A short story about FFS.
#+ROAM_TAGS: website creative-writing story science-fiction

I had quit my job at Valezon Technologies a week ago. They had decided that they wanted to put me on DS duty, I decided that they weren't worth working for anymore. My boss had yelled at me across his desk, I yelled back, all that jazz. Probably wouldn't work corp again.

I walked in to the chopper clinic and asked the doc what FFS would cost. I explained that I wanted my brow trimmed a bit. The doctor (well she called herself a doctor, can't totally be assured these days unless it's signed, and even then) excitedly looked at me, took a short scan of my face and showed me a list. It swam with vague numbers and names along with images of reconstructions and prices. It was really just like going to a hair cut, except she would cut up my skin and skull a bit as well.

I scrolled a bit and selected the Flurine 557 MM option. It seemed to result in the most feminine possible look, wasn't too expensive (though a bit pricey), and it seemed like it had good options. A few numbers didn't really make sense, but whatever, it was fine. She tapped a few buttons, asked me to count backwards from ten.

I woke up, slightly groggy, and with a series of targets were located in front of me.

"So I shaved your brow ridge a bit during the process and also installed the Flurine 557 micromissile system." said the chipper voice of the doctor over the intercom, "Here we have some targets lined up before you down range. Before I give you the certs and ammo for it, I want you to demonstrate that you can wield it safely."

I was nervous, I wanted Facial Feminization Surgery, not Facial Firearm Surgery, but it seems like she had given me both. I thought a bit about the targets, what they looked like, and envisioned a bullet impacting them. Then it did, a cold crack as the training missile popped before it hit the target.

For the next hour I focused in my woozy state on hitting various targets and not hitting others. I knew that she had messed up, but it felt very awkward to tell her that she had given how excited she seemed to be. Every time I passed a section I could almost hear her excitedly squee a bit before giving me further instructions. First it was a series of targets, then some aliens and some children, then what I was sure was a clip from some movie.

Eventually it was over and somehow the thought that I was out of ammunition (and the nearest store for ammunition) had popped into my brain.

Oh, of course, she probably ripped out some of my prefrontal cortex and whatever other bits of my brain were needed for the system and replaced it with a more compact computer, so it came with a BCI per-installed. Wonderful. I guess I had that coming eventually.

Eventually I passed, or something, because she came out of the area she was in and came out of whatever armored box she was in to chat with me.

"So now that it's over we're going to have to go back to my office."

"Wait, this isn't there?" Ireplied

"No, silly, this is the shooting range. If I were dedicated with FFS then I might have one, but, like, you were my first patient for that and it went really well. Like there's no scarring, your MCAP scores actually improved slightly even with bioident, and you have managed to hit the targets."

We went back to her office and she described to me the various features of the weapons system that she had scraped out some of my brain to install and how well I did. She was pretty, and her excitement was infectious.

"Hey, I'm a bit tired, and it's a bit late, can I sleep here?"

She blushed a bit. "Oh, sure, let me get the couch prepped, I don't normally have visitors."

I felt guilty, like I had been imposing on her a bit in this whole mess. She's a fucking doctor, chopper, whatever. She cuts people open and fixes them. She probably was just excited to see that everything worked. Our relationship was professional and I felt like shit for sort of pushing it into something that wasn't.

She ran upstairs and pulled some blankets down. I didn't know she slept here. Regardless I laid in the couch, waiting for the sunrise and my embarrassment to leave me.

I woke up in the morning, this time a bit sharper, and to an odd mixture of smells coming from a kitchen somewhere. I ambled over to the food area and she was preparing something that looked like a odd yellow mixture of shredded cabbage, and some other nameless things. It smelled sour, sweet, and thirty other things at once.

Once it is done we sat down to eat.

"I thought you were really pretty when I was operating on you." She said.

"Thanks" I replied, awkwardly, immediately recalculating the probability that she was a serial killer. I mean it was still low, but now more 1% low instead of 0.0001%.

"Uh, I don't mean it in that way, like it was really cool and."

"You're pretty too."

She blushed, and we both worked hard to quickly eat our food and say goodbys, executing all the formalities as quickly as possible.

I walked back, the speakers on the bus blaring. "Make Microintech Monitor your freecision today." and other such drivel. Some guys, I don't know where they were from, put a bullet into me. That hurt a lot. I shot a bullet (well micromissile™️) back, him in his head. He kept shooting and ran off, looking comically like a headless chicken and about as effective as one.

But it didn't matter, he had whatever set of self-repair that he had, I had those ripped out of me last week, so I sat there in the bus, bleeding onto the floor. Well until she appeared, or I was brought to her clinic, I am unsure on the order of those things.

She began to work on me, injecting me with some stabilizers, definitely some anesthetics because I couldn't feel a thing, and then ran a few machines to suture my wounds closed. Then I spent another night recovering at her place, and another day eating whatever strange things she had decided to cook.

After that I asked her if she needed someone to help her. I mean I could work with her a bit.
