#+TITLE: Website Source Code
#+DESCRIPTION: The source code for my blog, presented in a nice HTML file with commentary.
#+PROPERTY: header-args :noweb no-export
#+ROAM_TAGS: website public source-code

* Introduction
:PROPERTIES:
:ID:       e17fe4e7-f59a-4ad1-a525-aadc2f40b0ff
:PUBDATE:  <2021-04-03 Sat 22:11>
:END:
This is my the source code for my website. Currently it's only CSS, some emacs config, and a bit of HTML, but eventually I intend to add features for running ClojureScript in source code blocks among other things. Changes to this file will be noted in the [[file:changelog.org][changelog]].

The entire document is done in a nonlinear format, so each section does not exactly relate to an individual file, but rather combines the various files used into one. If you want to get to the code, just skip the intro and go straight to [[Lein Setup][Lein Setup]].

** Some History
:PROPERTIES:
:ID:       3e8bc3de-4215-417e-ba5e-1d2f1faf57b6
:END:
I have been blogging (and attempting to make websites) for a few years, however with each website I built I would run into a number of issues.

In the beginning my issue was HTML, CSS, and JavaScript. All of them sucked quite a bit.

Initially it was just that the blog was in markdown and had a somewhat messy system to generate it from the markdown files using ruby.

I have also recently been organizing my OS and system configuration into a giant wiki, so compatibility with that was also a necessary feature. I had attempted to do blogging in org mode before as well, though the [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]] option both lacked some features I wanted and left me with a somewhat lackluster experience when it came to linking files together. I probably was simply inexperienced, but it still left a bad taste in my mouth and didn't make me optimistic about the idea of having a public section to my personal wiki.

However, when I read about the org-publish feature, I was very interested in writing my own website with it. So far the simple export feature has been all that it was advertised to be and seems to be more than sufficient to make a good blog.

** Implementation Concept
:PROPERTIES:
:ID:       061344e2-ad27-486c-9e19-72b5c5b7c60c
:END:
The implementation itself is designed to be entirely local to this directory. So providing the org files should be roughly equivalent to providing the site itself (minus the color scheme of my Emacs configuration). It also adds free content if you will to the site.

* Lein Setup
:PROPERTIES:
:ID:       d913dcaa-31a7-4e14-93be-435777151a44
:PUBDATE:  <2021-04-03 Sat 22:11>
:END:
This sets up the Clojure project. Right now I don't actually really use the project per-se, but rather use it to generate CSS and HTML code from code blocks. Eventually I intend to add the ability to run ClojureScript in code blocks, but for now this works.
#+BEGIN_SRC clojure
(defproject cons-blog "1.0.0"
  :description "Generate HTML and CSS for org mode export."
  :dependencies [[org.clojure/clojure "1.10.2"]
                 <<stylesheet-deps>>
                 <<html-deps>>])
#+END_SRC


* Website Setup
:PROPERTIES:
:ID:       213aac54-d63a-4d6e-91a9-b319eac884e6
:PUBDATE:  <2021-04-03 Sat 22:11>
:END:
This is the Emacs Lisp code used to define the website. I use the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html][per-directory local variable]] functionality to set the ~org-html-publish~ settings.
** Website Info
:PROPERTIES:
:ID:       cb5d1a67-aae8-4752-a2f1-aa77c9d60e71
:END:
This gets the website info and sets the directories relative to the current one. It also sets the website name, adds the basic HTML publish / indent features, and excludes drafts from the project. (idea taken from [[https://www.john2x.com/blog/blogging-with-orgmode.html][John Louis Del Rosario]]).
#+NAME: emacs-site-info
#+BEGIN_SRC emacs-lisp
"(cons dev nil)"
:language "en"
:author "Inanna"
:exclude "level-.*\\|.*\.draft\.org"
:html-metadata-timestamp-format "%G-W%V-%u %H:%M"
:publishing-function org-html-publish-to-html
:html-html5-fancy t
:html-indent nil
#+END_SRC

** Source Directories
:PROPERTIES:
:ID:       1914d8ce-65d2-4ced-94e1-daaed92677e5
:END:
As of generating this file, thce directory above it contains the following files. 
#+BEGIN_SRC sh :exports results :results verbatim
ls ../ -nA
#+END_SRC

#+RESULTS:
#+begin_example
total 36
-rw-r--r-- 1 1000 998  114 Mar 30 16:31 .cider-repl-history
-rw-r--r-- 1 1000 998 1752 Apr  3 20:57 dir-locals.el
drwxr-xr-x 8 1000 998 4096 Apr  3 21:10 .git
-rw-r--r-- 1 1000 998  240 Apr  3 20:57 .gitignore
-rw-r--r-- 1 1000 998    5 Apr  3 20:57 .nrepl-port
-rw-r--r-- 1 1000 998  209 Mar 28 22:16 project.clj
drwxr-xr-x 4 1000 998 4096 Apr  3 20:58 public
drwxr-xr-x 2 1000 998 4096 Apr  3 20:49 src
drwxr-xr-x 4 1000 998 4096 Apr  3 20:57 target
#+end_example

The ~project.clj~ and ~target~ directories are automatically generated as are the dotfiles, while the ~src~ and ~public~ directories are not generated by any code. The ~src~ directory of course contains the org files while the ~public~ contains exported HTML. We set variables for these since the [[Automatic Publishing Function][automatic publishing function]] (WIP) also needs to know the directories. To find the location of the project itself I use [[https://github.com/bbatsov/projectile][projectile]].
#+NAME: emacs-directories
#+BEGIN_SRC emacs-lisp
(cd-source-dir (concat (projectile-project-root) "src/"))
(cd-publish-dir (concat (projectile-project-root) "public/"))
#+END_SRC

Here we add them to the project configuration. The ~:base-directory~ property is source for the project and the ~:publishing-directory~ is where the results of exporting are to be placed.
#+NAME: emacs-site-files
#+BEGIN_SRC emacs-lisp
:base-directory ,cd-source-dir
:publishing-directory ,cd-publish-dir
#+END_SRC

** Domain Data
:PROPERTIES:
:ID:       5e5cfeb1-a8b9-486b-8649-df5fae1b3b1b
:END:
This adds the CNAME data to the file. This is required for the site to serve properly under the A record I set up for it.
#+BEGIN_SRC text :tangle ../public/CNAME
cons.dev
#+END_SRC

** Sitemap
:PROPERTIES:
:ID:       69529e3e-8001-4060-83e9-c59e312e6c7b
:END:
This configures the sitemap title and name. It is automatically generated for all pages to make my life easier. Currently I use a flat layout for my website, so it is simply a list of all nodes. Eventually I want it to be displayed as a graph of links.
#+NAME: emacs-sitemap
#+BEGIN_SRC emacs-lisp
:sitemap-title "Sitemap"
:auto-sitemap t
#+END_SRC

** TODO Automatic Publishing Function
:PROPERTIES:
:ID:       68630630-f9a1-4382-b49b-8ec26c02695d
:END:
This will eventually automatically publish files. Currently it is WIP and is published primarily because it realtes to my [[file:namespace-el.org][emacs namespacing adventures]].

The assumption in the design is that I only really need to see the diff on the org files and the HTML files will sort themselves out. Therefore I just create a magit commit and do the job from there. The only issue is that the magit functions simply create buffers. I think the solution is to create a function to temporarily modify the hooks run after some of the functions.
#+BEGIN_SRC emacs-lisp
(defun cd-publish-files ()
  (interactive)
  (org-publish "(cons dev nil)")
  (cd cd-source-dir)
  (shell-command-to-string (format "git add '%s'" cd-source-dir))
  (magit-commit-create)
  ;(magit-git-push "main" "origin" "origin")
  (cd cd-publish-dir)
  (shell-command-to-string (format "git add '%s'" cd-publish-dir))
  (shell-command-to-string "git commit -m 'Automatically published, check website-src for details.'")
  (magit-git-push "main" "origin" "origin"))
#+END_SRC

*** The ~after-change~ Function                   :noexport:
:PROPERTIES:
:ID:       f1e11b1f-a78c-4409-9157-da91624389f8
:END:
Because this is 

In order to solve this I have found that you can 

** TODO Cleaning Broken Internal Links           :noexport:
:PROPERTIES:
:ID:       210dc246-af87-436e-b7ae-ba9fd741beb3
:END:
Because this is meant to be a mixture of blog and public portion of my personal wiki, I have some links to internal documents.

** Directory Local Variables
:PROPERTIES:
:ID:       2d81e220-7f6a-4544-9180-77ab3fa18990
:END:
This is the setup of the dir locals for the blog. They are used to keep the entire project local to the current directory.
#+BEGIN_SRC emacs-lisp :tangle ../dir-locals.el
((nil . ((eval
          . (progn
              (setq lexical-binding t)
              (lexical-let (
                    <<emacs-directories>>)
                <<auto-publish-command>>
                (setq
                 org-publish-project-alist
                 `((
                    <<emacs-site-info>>
                    <<emacs-sitemap>>
                    <<emacs-site-files>>
                    <<emacs-preamble>>
                    <<emacs-postamble>>
                    <<emacs-idx-sitemap>>
                    <<emacs-stylesheet>>)))))))))
#+END_SRC

** Git Setup
:PROPERTIES:
:ID:       e66fde4c-cfc1-4cd0-b508-f3d54b901d89
:END:
This is basically the (rather small) amount of setup used to ensure that generated files are not included in the git repository. It also ignores draft files.
#+BEGIN_SRC gitignore :tangle ../.gitignore
.dir-locals.el
.gitignore
project.clj
public
.cider-repl-history        
,*.draft.org

# Lein related stuff                       
/target
/classes
/checkouts
profiles.clj
pom.xml
pom.xml.asc
,*.jar
,*.class
/.lein-*
/.nrepl-port
/.prepl-port
#+END_SRC

* TODO ClojureScript Execution                    :noexport:
:PROPERTIES:
:ID:       aadf750f-6314-48a8-a32b-b335c21765be
:PUBDATE:  <2021-04-03 Sat 22:11>
:END:
This allows you to click "run" on the various ClojureScript codeblocks and get results from them.

** Approach Limitations
:PROPERTIES:
:ID:       ccc56d7e-960b-4cf8-8f91-3264546dc1b9
:END:
I have yet to add a system to automatically produce highlighted source code from it (which would be useful for demonstrating macroexpansion).

The system currently works through parsing the code block itself as source code and then executing that. The advantage to this is that it is way simpler to implement (I don't have to break into Emacs and start modifying the HTML export function), but it also means it doesn't recognize noweb syntax. 

This is /pretty much/ good enough for my purposes, though I would prefer to eventually add noweb support.

** Dependencies
:PROPERTIES:
:ID:       62f7b1fb-66d9-4ece-8253-18d6f340559d
:END:
Here we add some code to lein to make our lives easier.  
#+NAME: clojurescript-deps
#+BEGIN_SRC

#+END_SRC

* HTML
:PROPERTIES:
:ID:       e35862d9-423e-454b-b941-76207657baf6
:PUBDATE:  <2021-04-03 Sat 22:11>
:END:
This is where I configure the HTML displayed by the system.

** Dependencies
:PROPERTIES:
:ID:       c8112457-a095-4c98-8e18-2e8d0da7e4ca
:END:
Here we import hiccup so we can write our HTML in Clojure.
#+NAME: html-deps.
#+BEGIN_SRC clojure
[hiccup "1.0.5"]
#+END_SRC

** Preamble and Postamble
:PROPERTIES:
:ID:       9ffdbc0f-f6bd-4f27-ac6f-edc124c70854
:END:
This is the first section of the program and the

*** License Info
:PROPERTIES:
:ID:       4fd42343-09fa-4147-bf9e-eecb8d1edadf
:END:
This is the license info for my website. I selected the license because it provides one-way compatibility with the GPL-3.0 license. Thus I can license my code under the GPL, while licensing most of the text of the site under the [[https://creativecommons.org/licenses/by-sa/4.0/][CC-BY-SA 4.0 license]]. Currently it is displayed in the postamble on all pages, though I might want to alter that someday.

#+NAME: license-info
#+BEGIN_SRC clojure :results verbatim
[:p {:class "license"}
 "Except where otherwise noted content on "
 [:a {:href "https://cons.dev"} "cons.dev"]
 " is licensed under a "
 [:a {:rel "license" :href "https://creativecommons.org/licenses/by-sa/4.0/"}
  "Creative Commons Attribution-ShareAlike 4.0 International License"] "."]
#+END_SRC

*** Preamble
:PROPERTIES:
:ID:       83ec2c2a-0ade-4cc1-bb1d-7c3520b4ee93
:END:
This adds a few links to the beginning of the document to aid with navigation.
#+NAME: emacs-html-preamble
#+BEGIN_SRC clojure :results verbatim
(use 'hiccup.core)
(html [:a {:href "index.html"} "MAIN INDEX"]
      " | "
      [:a {:href "sitemap.html"} "SITEMAP"]
      " | "
      [:a {:href "https://github.com/cons-dev/website-src"} "SOURCE CODE (git)"])
#+END_SRC

This is the Emacs code that sets the preamble
#+NAME: emacs-preamble
#+BEGIN_SRC emacs-lisp
:html-preamble t
:html-preamble-format '("en" <<emacs-html-preamble()>>)
#+END_SRC

*** Postamble
:PROPERTIES:
:ID:       91179f88-cd71-4444-996a-515f05db124a
:END:
The end of each document this adds a little bit of text containing the info about the program that created it, the date the file was modified, and licensing information
#+NAME: emacs-html-postamble
#+BEGIN_SRC clojure :results verbatim
(use 'hiccup.core)
(html [:p {:class "date"} "Last Modified: %C"]
      [:p {:class "creator"} "Generated Using: %c"]
       <<license-info>>)
#+END_SRC

This code sets the postamble.
#+NAME: emacs-postamble
#+BEGIN_SRC emacs-lisp
:html-postamble t
:html-postamble-format '("en" <<emacs-html-postamble()>>)
#+END_SRC


* Stylesheets
:PROPERTIES:
:ID:       a98f1437-8108-4de2-92c1-2f28b3ad72ad
:PUBDATE:  <2021-04-03 Sat 22:11>
:END:
While [[https://orgmode.org/manual/HTML-Export.html#HTML-Export][org-html-export]] does an admirable job at exporting code in my preferred syntax highlighting style, it unfortunately does not replicate the other features of my org-mode buffers. To do that I use [[https://github.com/noprompt/garden][Garden]], a Clojure library for rendering CSS.

The reason I use garden is mostly because I dislike using CSS directly or.

** Emacs Configuration
:PROPERTIES:
:ID:       9e5769bf-5eaf-45b1-a300-07592fd02cfb
:END:
This adds the Emacs configuration for the stylesheets in the blog. It also adds a link to the fonts stylesheet.
#+NAME: stylesheet-html
#+BEGIN_SRC clojure :results verbatim
(use 'hiccup.core)
(html [:link {:rel "stylesheet" :type "text/css" :href "site.css"}])
#+END_SRC
This property then sets the HTML head on every file to be the HTML generated by that.
#+NAME: emacs-stylesheet
#+BEGIN_SRC emacs-lisp
:html-head <<stylesheet-html()>>
#+END_SRC

** Create CSS File
:PROPERTIES:
:ID:       6dc27afd-b4f7-477c-8ef1-2d5f809eae9b
:END:
This creates the CSS file in my public directory. It is automatically called every time the project is updated (thus generating the CSS file). This ensures that the state of this file is kept in sync with the actual state of the project itself.
#+NAME: stylesheet
#+BEGIN_SRC clojure :results silent
(ns stylesheets
  "A namespace for stylesheets"
  (:require [garden.core :refer [css]]
            [garden.def :refer [defcssfn]]
            [garden.selectors :refer [defpseudoelement
                                      defselector]]
            [garden.stylesheet :refer [at-import]]))

(defcssfn url)
(defpseudoelement selection)
(defselector pre)
(defselector p)
(defselector a)

(spit "./public/site.css"
      (css
       <<stylesheet-font-face>>
       <<stylesheet-default>>
       <<stylesheet-todo>>
       <<stylesheet-selection>>
       <<stylesheet-headlines>>
       <<stylesheet-info>>
       <<stylesheet-links>>
       <<stylesheet-src-hover-info>>
       <<stylesheet-src-block>>))
#+END_SRC

#+CALL: stylesheet()

** Default Background and Foreground
:PROPERTIES:
:ID:       69ed328f-0e34-41b3-9712-ce4ef735e9bd
:END:
This keeps the default background and foreground in sync with the rest of the system. To see the code blocks being called, view the [[Helper Code Blocks][helper blocks]] section. I also set up the font I use here, in this case [[https://typeof.net/Iosevka/][Iosevka]], a pleasing DIN-like font that is entirely fixed-width for use in terminals.

The Iosevka Term Web font itself provides a [[file:iosevka-term-css.org][css file]] that works rather well. 
#+NAME: stylesheet-default
#+BEGIN_SRC clojure
(at-import (url "fonts/iosevka-term.css"))
[:body {:background-color <<face-bg(face="default")>>
        :color            <<face-fg(face="default")>>
        :font-family      "'Iosevka Term Web'"}]
[:code {:color <<face-fg(face="org-code")>>}]
#+END_SRC

** Todo Items
:PROPERTIES:
:ID:       e0a94046-9974-4b03-bdf8-649dbbe9a95d
:END:
This fixes the coloration of TODO keywords in headers. Initally they are a somewhat ugly red color.
#+NAME: stylesheet-todo
#+BEGIN_SRC clojure
[:.todo {:color <<face-fg(face="org-todo")>>}]
[:.done {:color <<face-fg(face="org-headline-done")>>}]
#+END_SRC

** Selected Text
:PROPERTIES:
:ID:       060fe53e-ad37-4f94-a88e-5e9d460d501e
:END:
This makes the text selection look good using the [[https://developer.mozilla.org/en-US/docs/Web/CSS/::selection][selection]] pseudo-element.
#+NAME: stylesheet-selection
#+BEGIN_SRC clojure
[(selection) {:background-color <<face-bg(face="region")>>
              :color            'none}]
#+END_SRC

** Headlines
:PROPERTIES:
:ID:       e3209f7d-fe3b-42f1-8143-b7cf7c8023dd
:END:
Here I restyle the headlines using the style I currently use in Emacs. These code blocks automatically fetch them and return a string that can be inserted.
#+NAME: stylesheet-headlines
#+BEGIN_SRC clojurescript
[:h2 {:color <<face-fg(face="outline-1")>>}]
[:h3 {:color <<face-fg(face="outline-2")>>}]
[:h4 {:color <<face-fg(face="outline-3")>>}]
#+END_SRC

** Author and Title Information
:PROPERTIES:
:ID:       d4f2a79b-ffca-492a-bd0a-4cf33983972b
:END:
The title, date, and author information in Emacs are usually the same color. So I set them here.
#+NAME: stylesheet-info
#+BEGIN_SRC clojure
`[~@(map p [".author" ".date" ".creator" ".license"])
  {:color <<face-fg(face="org-document-info")>>}]
[:.title {:font-style 'italic
          :color      <<face-fg(face="org-document-title")>>}]
[:.subtitle {:font-style 'normal}]
#+END_SRC


*** Blocks
:PROPERTIES:
:ID:       bf7d5bb5-42e5-454f-9271-3f60abdc800c
:END:
This removes the irritating border and shadow from the code blocks.
#+NAME: stylesheet-src-block
#+BEGIN_SRC clojure
[(pre ".src") {:background-color <<face-bg(face="org-block")>>}]
[:pre {:top        0
       :right      0
       :box-shadow 'none
       :border     'none}]
#+END_SRC

*** Hover Info
:PROPERTIES:
:ID:       e41af7c2-6a90-4ac6-a1e0-b40b451c5410
:END:
This adds the hover info to ClojureScript, which was not included by default.
#+NAME: stylesheet-src-hover-info
#+BEGIN_SRC clojure
[(pre ".src-clojurescript" ":before")
 {:content "'ClojureScript'"}]
[(pre ".src" ":hover" ":before")
 {:display    'inline
  :background-color <<face-bg(face="default")>>
  :margin-top       "14px"
  :border           'none}]
#+END_SRC

** Links
:PROPERTIES:
:ID:       1cbee566-7c24-4b67-a31b-3cb47edb193f
:END:
This stylizes links to match the links in Emacs org-mode buffers.
#+NAME: stylesheet-links
#+BEGIN_SRC clojure
[(a ":link") {:color <<face-fg(face="link")>>}]
[(a ":visited") {:color <<face-fg(face="link-visited")>>}]
[(a ":hover")
 {:color            <<face-bg(face="default")>>
  :background-color <<face-fg(face="link")>>
  :text-decoration  'none}]
[(a ":active")
 {:color            <<face-bg(face="default")>>
  :background-color <<face-fg(face="link")>>
  :text-decoration  'none}]
#+END_SRC

** Helper Code Blocks
:PROPERTIES:
:ID:       7f295124-cbb1-4f6f-8abe-f668c1500057
:END:
These are little helper code blocks that fetch the face attributes I want automatically from emacs every time I regenerate the file. This ensures that my code remains in-sync with my Emacs configuration style.

This code block simply extracts the foreground color. Mostly used for headlines, but also for text in general.
#+NAME: face-fg
#+BEGIN_SRC emacs-lisp :results verbatim
(face-attribute (intern face) :foreground)
#+END_SRC

This finds the background color of a face. Mostly this just extracts colors for source code block backgrounds and the backgrounds for the main text documents.
#+NAME: face-bg
#+BEGIN_SRC emacs-lisp :results verbatim
(face-attribute (intern face) :background)
#+END_SRC
